export default {
  login: "gnikita432",
  id: 61223163,
  node_id: "MDQ6VXNlcjYxMjIzMTYz",
  avatar_url: "https://avatars.githubusercontent.com/u/61223163?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/gnikita432",
  html_url: "https://github.com/gnikita432",
  followers_url: "https://api.github.com/users/gnikita432/followers",
  following_url:
    "https://api.github.com/users/gnikita432/following{/other_user}",
  gists_url: "https://api.github.com/users/gnikita432/gists{/gist_id}",
  starred_url: "https://api.github.com/users/gnikita432/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/gnikita432/subscriptions",
  organizations_url: "https://api.github.com/users/gnikita432/orgs",
  repos_url: "https://api.github.com/users/gnikita432/repos",
  events_url: "https://api.github.com/users/gnikita432/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/gnikita432/received_events",
  type: "User",
  site_admin: false,
  name: "Nikita Anil Gupta",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 33,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2020-02-19T06:36:53Z",
  updated_at: "2021-05-20T10:26:10Z",
};
